
services:
  web:
    build: .
    ports:
      - "59998:59998"
    volumes:
      - .:/app
      - ./data:/app/data
    environment:
      - FLASK_ENV=development
      - SERVER-IP1=192.168.0.104
      - SERVER-IP2=192.168.0.104